import { useState, useEffect } from "react";
import { useNavigate } from "react-router";
import { useUserProfile } from "../hooks/useUserProfile";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { Download, Calendar, Clock, MapPin, User, CheckCircle, ArrowLeft } from "lucide-react";
import logoImg from "../../assets/watchtower-logo.svg";

/** Parse a combined day string like "MW" or "TuTh" into individual abbreviations. */
function parseDays(courseDays: string): string[] {
  return courseDays.match(/Tu|Th|Sa|[MWFS]/g) ?? [];
}

function matchesDay(courseDays: string, gridDay: string): boolean {
  return parseDays(courseDays).includes(gridDay);
}

// TODO: hardcoded - replace with real schedule options generated by the backend schedule engine
const SCHEDULE_OPTIONS = [
  {
    id: 1,
    name: "Optimized Schedule",
    matchScore: 95,
    courses: [
      {
        code: "CSCI 335",
        title: "Data Structures & Algorithms",
        section: "01",
        instructor: "Dr. Sarah Johnson",
        days: "MW",
        time: "10:00 AM - 11:30 AM",
        location: "North 1001",
        credits: 4,
      },
      {
        code: "CSCI 360",
        title: "Computer Architecture",
        section: "02",
        instructor: "Prof. Michael Chen",
        days: "TuTh",
        time: "2:00 PM - 3:30 PM",
        location: "North 1007",
        credits: 3,
      },
      {
        code: "MATH 260",
        title: "Linear Algebra",
        section: "03",
        instructor: "Dr. Emily Rodriguez",
        days: "MW",
        time: "12:00 PM - 1:30 PM",
        location: "Hunter West 620",
        credits: 4,
      },
      {
        code: "ENGL 220",
        title: "Writing Intensive Core",
        section: "05",
        instructor: "Prof. David Kim",
        days: "TuTh",
        time: "10:00 AM - 11:30 AM",
        location: "Hunter West 405",
        credits: 3,
      },
    ],
    totalCredits: 14,
    daysOnCampus: 4,
    highlights: [
      "No early morning classes",
      "Lunch break every day",
      "High-rated professors",
    ],
  },
  {
    id: 2,
    name: "Compact Schedule",
    matchScore: 88,
    courses: [
      {
        code: "CSCI 335",
        title: "Data Structures & Algorithms",
        section: "03",
        instructor: "Dr. James Wilson",
        days: "TuTh",
        time: "9:00 AM - 10:30 AM",
        location: "North 1001",
        credits: 4,
      },
      {
        code: "CSCI 360",
        title: "Computer Architecture",
        section: "01",
        instructor: "Dr. Lisa Brown",
        days: "TuTh",
        time: "11:00 AM - 12:30 PM",
        location: "North 1005",
        credits: 3,
      },
      {
        code: "MATH 260",
        title: "Linear Algebra",
        section: "01",
        instructor: "Prof. Robert Taylor",
        days: "TuTh",
        time: "2:00 PM - 3:30 PM",
        location: "Hunter West 618",
        credits: 4,
      },
      {
        code: "ENGL 220",
        title: "Writing Intensive Core",
        section: "08",
        instructor: "Dr. Amanda Lee",
        days: "MW",
        time: "1:00 PM - 2:30 PM",
        location: "Hunter West 412",
        credits: 3,
      },
    ],
    totalCredits: 14,
    daysOnCampus: 4,
    highlights: [
      "Only 2 days per week",
      "Back-to-back classes",
      "Free Mondays and Wednesdays",
    ],
  },
  {
    id: 3,
    name: "Balanced Schedule",
    matchScore: 82,
    courses: [
      {
        code: "CSCI 335",
        title: "Data Structures & Algorithms",
        section: "02",
        instructor: "Prof. Jennifer Martinez",
        days: "MW",
        time: "3:00 PM - 4:30 PM",
        location: "North 1003",
        credits: 4,
      },
      {
        code: "CSCI 360",
        title: "Computer Architecture",
        section: "03",
        instructor: "Dr. Kevin Wang",
        days: "TuTh",
        time: "12:30 PM - 2:00 PM",
        location: "North 1009",
        credits: 3,
      },
      {
        code: "MATH 260",
        title: "Linear Algebra",
        section: "02",
        instructor: "Dr. Patricia Garcia",
        days: "MW",
        time: "11:00 AM - 12:30 PM",
        location: "Hunter West 622",
        credits: 4,
      },
      {
        code: "ENGL 220",
        title: "Writing Intensive Core",
        section: "06",
        instructor: "Prof. Christopher Davis",
        days: "TuTh",
        time: "3:00 PM - 4:30 PM",
        location: "Hunter West 408",
        credits: 3,
      },
    ],
    totalCredits: 14,
    daysOnCampus: 4,
    highlights: [
      "Spread across the week",
      "Moderate start times",
      "Consistent daily schedule",
    ],
  },
];

export function ViewSchedules() {
  const navigate = useNavigate();
  const { email: userEmail } = useUserProfile();
  const [selectedSchedule, setSelectedSchedule] = useState(SCHEDULE_OPTIONS[0]);
  const [exportSuccess, setExportSuccess] = useState(false);

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, []);

  const handleExport = () => {
    setExportSuccess(true);
    // TODO: hardcoded - replace 3000ms with a UI_FEEDBACK_TIMEOUT constant from app config
    setTimeout(() => setExportSuccess(false), 3000);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 to-blue-100">
      <header className="bg-white/95 backdrop-blur-md border-b border-gray-200/50 sticky top-0 z-10 shadow-sm">
        <div className="max-w-screen-2xl mx-auto px-4 lg:px-6 py-5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <img src={logoImg} alt="Watchtower Logo" className="h-16 w-auto" />
          </div>
          <div className="flex items-center gap-6">
            <span className="text-lg text-gray-600 font-medium">{userEmail}</span>
            <Button variant="outline" onClick={() => navigate("/dashboard")} className="border-gray-300 hover:border-gray-400 hover:bg-gray-50 transition-colors text-base px-4 py-2">
              Dashboard
            </Button>
          </div>
        </div>
      </header>

      <main className="max-w-screen-2xl mx-auto px-4 lg:px-6 py-10">
        <Button variant="ghost" size="sm" onClick={() => navigate("/preferences")} className="mb-8 hover:bg-white/60 text-gray-600 hover:text-gray-800 transition-all">
          <ArrowLeft className="size-4 mr-2" />
          Back to Preferences
        </Button>

        <div className="mb-10">
          <div className="flex items-center gap-3 mb-4">
            <CheckCircle className="size-8 text-green-600" />
            <h2 className="text-4xl font-bold text-gray-900">Your Generated Schedules</h2>
          </div>
          <p className="text-xl text-gray-600 leading-relaxed">
            We found {SCHEDULE_OPTIONS.length} conflict-free schedules that match your preferences and requirements
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          <div className="lg:col-span-1 space-y-5">
            {SCHEDULE_OPTIONS.map((schedule) => (
              <Card
                key={schedule.id}
                className={`cursor-pointer transition-all shadow-md border-0 bg-white/90 backdrop-blur-sm ${
                  selectedSchedule.id === schedule.id
                    ? "ring-2 ring-purple-500 shadow-lg"
                    : "hover:shadow-lg"
                }`}
                onClick={() => setSelectedSchedule(schedule)}
              >
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between">
                    <CardTitle className="text-xl">{schedule.name}</CardTitle>
                    <Badge
                      variant={schedule.id === 1 ? "default" : "secondary"}
                      className={`text-sm px-3 py-1 ${schedule.id === 1 ? "bg-green-600" : ""}`}
                    >
                      {schedule.matchScore}% Match
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2 text-lg">
                    <div className="flex justify-between">
                      <span className="text-gray-600">Total Credits</span>
                      <span className="font-semibold">{schedule.totalCredits}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Days on Campus</span>
                      <span className="font-semibold">{schedule.daysOnCampus}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Courses</span>
                      <span className="font-semibold">{schedule.courses.length}</span>
                    </div>
                  </div>
                  <div className="mt-4 pt-4 border-t border-gray-200">
                    <ul className="space-y-2">
                      {schedule.highlights.slice(0, 2).map((highlight, idx) => (
                        <li key={idx} className="text-base text-gray-600 flex items-center gap-2">
                          <span className="text-purple-600 font-bold">•</span>
                          {highlight}
                        </li>
                      ))}
                    </ul>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <div className="lg:col-span-2 space-y-6">
            <Card className="shadow-lg border-0 bg-white/90 backdrop-blur-sm">
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="text-2xl">{selectedSchedule.name}</CardTitle>
                    <CardDescription className="text-lg mt-2">
                      {/* TODO: hardcoded - replace semester label with selected semester from user preferences */}
                      Fall 2026 • {selectedSchedule.totalCredits} credits
                    </CardDescription>
                  </div>
                  <Button size="lg" onClick={handleExport} className="text-base">
                    <Download className="size-4 mr-2" />
                    {exportSuccess ? "Exported!" : "Export"}
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <div className="bg-green-50 border border-green-200 rounded-xl p-5 mb-6">
                  <h4 className="text-lg font-semibold text-green-900 mb-3">Why this schedule works:</h4>
                  <ul className="space-y-2">
                    {selectedSchedule.highlights.map((highlight, idx) => (
                      <li key={idx} className="text-lg text-green-800 flex items-center gap-2">
                        <CheckCircle className="size-5 flex-shrink-0" />
                        {highlight}
                      </li>
                    ))}
                  </ul>
                </div>

                <Tabs defaultValue="list" className="w-full">
                  <TabsList className="grid w-full grid-cols-2">
                    <TabsTrigger value="list" className="text-base">Course List</TabsTrigger>
                    <TabsTrigger value="calendar" className="text-base">Calendar View</TabsTrigger>
                  </TabsList>
                  <div className="mt-2 flex items-center gap-2 text-base text-gray-600">
                    <Calendar className="size-4" />
                    <span>Calendar includes Saturday • Hourly time slots for precise scheduling</span>
                  </div>
                  <TabsContent value="list" className="space-y-4 mt-6">
                    {selectedSchedule.courses.map((course) => (
                      <Card key={`${course.code}-${course.section}`} className="shadow-sm border border-gray-200">
                        <CardContent className="pt-6">
                          <div className="flex items-start justify-between mb-4">
                            <div>
                              <h4 className="font-bold text-xl">
                                {course.code} - {course.title}
                              </h4>
                              <p className="text-lg text-gray-600 mt-1">Section {course.section}</p>
                            </div>
                            <Badge className="text-base px-3 py-1">{course.credits} credits</Badge>
                          </div>

                          <div className="grid md:grid-cols-2 gap-4 text-lg">
                            <div className="flex items-center gap-2 text-gray-700">
                              <User className="size-5 flex-shrink-0" />
                              <span>{course.instructor}</span>
                            </div>
                            <div className="flex items-center gap-2 text-gray-700">
                              <Calendar className="size-5 flex-shrink-0" />
                              <span>{course.days}</span>
                            </div>
                            <div className="flex items-center gap-2 text-gray-700">
                              <Clock className="size-5 flex-shrink-0" />
                              <span>{course.time}</span>
                            </div>
                            <div className="flex items-center gap-2 text-gray-700">
                              <MapPin className="size-5 flex-shrink-0" />
                              <span>{course.location}</span>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    ))}
                  </TabsContent>

                  <TabsContent value="calendar" className="mt-6">
                    <div className="bg-white rounded-xl border border-gray-200 overflow-hidden shadow-sm">
                      <div className="grid grid-cols-7 border-b border-gray-200">
                        <div className="p-4 bg-gray-50 border-r border-gray-200 text-sm font-semibold text-gray-600">
                          TIME
                        </div>
                        {/* TODO: hardcoded - replace with DAYS constant shared with SetPreferences.tsx */}
                        {["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].map((day) => (
                          <div key={day} className="p-4 bg-gray-50 border-r border-gray-200 last:border-r-0 text-center font-semibold text-base">
                            {day.slice(0, 3)}
                          </div>
                        ))}
                      </div>

                      {/* TODO: hardcoded - replace with TIME_SLOTS constant shared with SetPreferences.tsx */}
                      {["7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM"].map((time) => (
                        <div key={time} className="grid grid-cols-7 border-b border-gray-200 last:border-b-0 min-h-[60px]">
                          <div className="p-3 bg-gray-50 border-r border-gray-200 text-sm text-gray-600 font-medium flex items-center">
                            {time}
                          </div>
                          {["M", "Tu", "W", "Th", "F", "Sa"].map((day) => {
                            const course = selectedSchedule.courses.find(
                              (c) => matchesDay(c.days, day) && c.time.startsWith(time)
                            );
                            return (
                              <div key={day} className="p-1 border-r border-gray-200 last:border-r-0 relative">
                                {course && (
                                  <div className="bg-gradient-to-r from-purple-100 to-blue-100 border border-purple-300 rounded-md p-2 h-full shadow-sm hover:shadow-md transition-shadow">
                                    <p className="font-semibold text-xs text-purple-900 truncate">{course.code}</p>
                                    <p className="text-xs text-purple-700 mt-1 truncate">{course.location}</p>
                                    <div className="absolute -top-1 -right-1 w-2 h-2 bg-purple-500 rounded-full"></div>
                                  </div>
                                )}
                              </div>
                            );
                          })}
                        </div>
                      ))}
                    </div>
                  </TabsContent>
                </Tabs>
              </CardContent>
            </Card>

            <Card className="shadow-lg border-0 bg-white/90 backdrop-blur-sm">
              <CardHeader className="pb-4">
                <CardTitle className="text-2xl">Next Steps</CardTitle>
                <CardDescription className="text-lg mt-2">Ready to register for these courses?</CardDescription>
              </CardHeader>
              <CardContent className="pt-2">
                <div className="space-y-4">
                  <Button className="w-full h-14 text-lg font-semibold bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 shadow-lg hover:shadow-xl transition-all duration-200" size="lg">
                    <Calendar className="size-5 mr-2" />
                    Export to Calendar
                  </Button>
                  <Button variant="outline" className="w-full h-14 text-lg font-semibold border-gray-300 hover:border-gray-400 hover:bg-gray-50 transition-colors" size="lg">
                    Open CUNYfirst to Register
                  </Button>
                  <Button variant="outline" className="w-full h-12 text-base font-semibold border-gray-300 hover:border-gray-400 hover:bg-gray-50 transition-colors" onClick={() => navigate("/preferences")}>
                    Adjust Preferences
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}
