spring.application.name=watchtower
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url=jdbc:postgresql://${spring.datasource.username}.supabase.co:5432/postgres?user=postgres&password=${spring.datasource.password}&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver