spring.application.name=watchtower
spring.datasource.username=insert-username
spring.datasource.password=insert-password
spring.datasource.url=jdbc:postgresql://${spring.datasource.username}.supabase.co:5432/postgres?user=postgres&password=${spring.datasource.password}&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver