spring.application.name=watchtower
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.session.store-type=none
spring.datasource.driver-class-name=org.postgresql.Driver